#%RAML 1.0 DataType
type: array
items:
  properties:    
    sno:
      type: string
      required: true
      example: "222"
    sname:
      type: string | nil
      required: false
    sage:
      type: string
      required: false
    semail:
      type: string
      required: true
    saddress: 
      type: string
      required: false